name = "ISAP_v1"
description = "Implementation of isapa128av20 and asconhashv12 with W=32 and CCW=32"


dependencies = [
	{ uri = "git+https://github.com/GMUCERG/LWC.git#hardware/LWC_2Pass_32.toml", rtl.pos = 1 },
]

[language]
vhdl.standard = "2008"
vhdl.synopsys = false

[rtl]

sources = [
	"src_rtl/v1/design_pkg.vhd",
	# "src_rtl/LWC_config_32.vhd",
	# "src_rtl/LWC/NIST_LWAPI_pkg.vhd",
	"src_rtl/v1/CryptoCore.vhd",
	# "src_rtl/LWC/PISO.vhd",
	# "src_rtl/LWC/SIPO.vhd",
	# "src_rtl/LWC/FIFO.vhd",
	# "src_rtl/LWC/PreProcessor.vhd",
	# "src_rtl/LWC/PostProcessor.vhd",
	# "src_rtl/LWC/LWC_2Pass.vhd",
]
# top = 'LWC_2pass'
clock.port = "clk"

# [tb]
# top = 'LWC_TB'
# sources = [
# 	"/Users/kamyar/src/lwc/LWC/hardware/LWC_tb/LWC_TB_2pass_uut.vhd", 
# 	"/Users/kamyar/src/lwc/LWC/hardware/LWC_tb/LWC_TB.vhd"
# ]

[tb.generics]
G_FNAME_PDI.file = "KAT/v1/pdi.txt"
G_FNAME_SDI.file = "KAT/v1/sdi.txt"
G_FNAME_DO.file =  "KAT/v1/do.txt"
# G_FNAME_PDI.file = "BENCH_KAT/ISAP_v1/timing_tests/pdi.txt"
# G_FNAME_SDI.file = "BENCH_KAT/ISAP_v1/timing_tests/sdi.txt"
# G_FNAME_DO.file  = "BENCH_KAT/ISAP_v1/timing_tests/do.txt"
# G_FNAME_PDI.file = "BENCH_KAT/ISAP_v1/kats_for_verification/pdi.txt"
# G_FNAME_SDI.file = "BENCH_KAT/ISAP_v1/kats_for_verification/sdi.txt"
# G_FNAME_DO.file  = "BENCH_KAT/ISAP_v1/kats_for_verification/do.txt"
G_TEST_MODE = 0
G_MAX_FAILURES = 0
G_TIMEOUT_CYCLES = 10_000
G_RANDOM_SEED = 1
G_PDI_STALLS = 7
G_SDI_STALLS = 13
G_DO_STALLS = 21
G_RANDOM_STALL = true              # true

[lwc]
aead.algorithm = "isapa128av20"
aead.key_reuse = true
aead.input_sequence.encrypt = ['npub', 'pt', 'ad', 'tag']
aead.input_sequence.decrypt = ['npub', 'ad', 'ct', 'tag']
hash.algorithm = "asconhashv12"

ports.pdi.bit_width = 32
ports.sdi.bit_width = 32
