name = "ISAPk_v2"
description = "Implementation of isapk128av20 with W=16 and CCW=16"

dependencies = [
    { uri = "git+https://github.com/GMUCERG/LWC.git#hardware/LWC_2Pass.toml", rtl.pos = 2 },
]


[language]
vhdl.standard = "2008"
vhdl.synopsys = false

[rtl]
sources = [
	"src_rtl/v2/design_pkg.vhd",
	"src_rtl/LWC_config_16.vhd",
    # "../../../LWC/hardware/LWC_rtl/NIST_LWAPI_pkg.vhd",
	# "src_rtl/LWC/NIST_LWAPI_pkg.vhd",
	"src_rtl/v2/CryptoCore.vhd",
	# "src_rtl/LWC/key_piso.vhd",
	# "src_rtl/LWC/FIFO.vhd",
	# "src_rtl/LWC/data_sipo.vhd",
	# "src_rtl/LWC/data_piso.vhd",
	# "src_rtl/LWC/PreProcessor.vhd",
	# "src_rtl/LWC/PostProcessor.vhd",
	# "src_rtl/LWC/LWC_2pass.vhd",
	# "../LWC_rtl/LWC_2Pass_uut.vhd",
    # "../../../LWC/hardware/LWC_rtl/PISO.vhd",
    # "../../../LWC/hardware/LWC_rtl/SIPO.vhd",
    # "../../../LWC/hardware/LWC_rtl/FIFO.vhd",
    # "../../../LWC/hardware/LWC_rtl/PreProcessor.vhd",
    # "../../../LWC/hardware/LWC_rtl/PostProcessor.vhd",
    # "../../../LWC/hardware/LWC_rtl/LWC_2Pass.vhd",
    # "../../../LWC/hardware/LWC_rtl/LWC_2Pass_uut.vhd",
]
# top = "LWC"
# clock.port = "clk"

# [tb]
# top = 'LWC_TB'
# sources = [
# 	# "src_tb/LWC_TB.vhd",
#     "../../../LWC/hardware/LWC_tb/LWC_TB.vhd",
# ]

# [tb.generics]
# G_FNAME_PDI.file = "KAT/v2/pdi.txt"
# G_FNAME_SDI.file = "KAT/v2/sdi.txt"
# G_FNAME_DO.file = "KAT/v2/do.txt"
# # G_FNAME_PDI.file = "BENCH_KAT/v2/timing_tests/pdi.txt"
# # G_FNAME_SDI.file = "BENCH_KAT/v2/timing_tests/sdi.txt"
# # G_FNAME_DO.file =  "BENCH_KAT/v2/timing_tests/do.txt"
# G_TEST_MODE = 0

[lwc]
aead.algorithm = "isapk128av20"
aead.key_reuse = true
aead.input_sequence.encrypt = ['npub', 'pt', 'ad', 'tag']
aead.input_sequence.decrypt = ['npub', 'ad', 'ct', 'tag']
# hash.algorithm = "asconhashv12"

ports.pdi.bit_width = 16
ports.sdi.bit_width = 16
